name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: EcePanos/panosci/.github/workflows/build.yml@main

  test:
    needs: build
    uses: EcePanos/panosci/.github/workflows/test.yml@main
