on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: image:latest
          outputs: type=docker, dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar

  build-tester:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      - name: Load image
        run: docker load -i /tmp/image.tar

      - name: Tag image
        run: docker tag $(docker images -q | head -n 1) image:latest

      - name: Build
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.test
          push: false
          tags: tester:latest
          outputs: type=docker, dest=/tmp/tester.tar
          build-args: |
            BASE_IMAGE=image:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tester
          path: /tmp/tester.tar

  test:
    runs-on: ubuntu-latest
    needs: build-tester
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tester
          path: /tmp

      - name: Load image
        run: docker load -i /tmp/tester.tar

      - name: Run tests
        run: docker run --rm tester:latest
